// Models.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

protocol JSONEncodable {
    func encodeToJSON() -> AnyObject
}

public enum ErrorResponse : ErrorType {
    case Error(Int, NSData?, ErrorType)
}

public class Response<T> {
    public let statusCode: Int
    public let header: [String: String]
    public let body: T?

    public init(statusCode: Int, header: [String: String], body: T?) {
        self.statusCode = statusCode
        self.header = header
        self.body = body
    }

    public convenience init(response: NSHTTPURLResponse, body: T?) {
        let rawHeader = response.allHeaderFields
        var header = [String:String]()
        for (key, value) in rawHeader {
            header[key as! String] = value as? String
        }
        self.init(statusCode: response.statusCode, header: header, body: body)
    }
}

private var once = dispatch_once_t()
class Decoders {
    static private var decoders = Dictionary<String, ((AnyObject) -> AnyObject)>()

    static func addDecoder<T>(clazz clazz: T.Type, decoder: ((AnyObject) -> T)) {
        let key = "\(T.self)"
        decoders[key] = { decoder($0) as! AnyObject }
    }

    static func decode<T>(clazz clazz: [T].Type, source: AnyObject) -> [T] {
        let array = source as! [AnyObject]
        return array.map { Decoders.decode(clazz: T.self, source: $0) }
    }

    static func decode<T, Key: Hashable>(clazz clazz: [Key:T].Type, source: AnyObject) -> [Key:T] {
        let sourceDictionary = source as! [Key: AnyObject]
        var dictionary = [Key:T]()
        for (key, value) in sourceDictionary {
            dictionary[key] = Decoders.decode(clazz: T.self, source: value)
        }
        return dictionary
    }

    static func decode<T>(clazz clazz: T.Type, source: AnyObject) -> T {
        initialize()
        if T.self is Int32.Type && source is NSNumber {
            return source.intValue as! T;
        }
        if T.self is Int64.Type && source is NSNumber {
            return source.longLongValue as! T;
        }
        if T.self is NSUUID.Type && source is String {
            return NSUUID(UUIDString: source as! String) as! T
        }
        if source is T {
            return source as! T
        }
        if T.self is NSData.Type && source is String {
            return NSData(base64EncodedString: source as! String, options: NSDataBase64DecodingOptions()) as! T
        }

        let key = "\(T.self)"
        if let decoder = decoders[key] {
           return decoder(source) as! T
        } else {
            fatalError("Source \(source) is not convertible to type \(clazz): Maybe swagger file is insufficient")
        }
    }

    static func decodeOptional<T>(clazz clazz: T.Type, source: AnyObject?) -> T? {
        if source is NSNull {
            return nil
        }
        return source.map { (source: AnyObject) -> T in
            Decoders.decode(clazz: clazz, source: source)
        }
    }

    static func decodeOptional<T>(clazz clazz: [T].Type, source: AnyObject?) -> [T]? {
        if source is NSNull {
            return nil
        }
        return source.map { (someSource: AnyObject) -> [T] in
            Decoders.decode(clazz: clazz, source: someSource)
        }
    }

    static func decodeOptional<T, Key: Hashable>(clazz clazz: [Key:T].Type, source: AnyObject?) -> [Key:T]? {
        if source is NSNull {
            return nil
        }
        return source.map { (someSource: AnyObject) -> [Key:T] in
            Decoders.decode(clazz: clazz, source: someSource)
        }
    }

    static private func initialize() {
        dispatch_once(&once) {
            let formatters = [
                "yyyy-MM-dd",
                "yyyy-MM-dd'T'HH:mm:ssZZZZZ",
                "yyyy-MM-dd'T'HH:mm:ss.SSSZZZZZ",
                "yyyy-MM-dd'T'HH:mm:ss'Z'",
                "yyyy-MM-dd'T'HH:mm:ss.SSS"
            ].map { (format: String) -> NSDateFormatter in
                let formatter = NSDateFormatter()
                formatter.dateFormat = format
                return formatter
            }
            // Decoder for NSDate
            Decoders.addDecoder(clazz: NSDate.self) { (source: AnyObject) -> NSDate in
               if let sourceString = source as? String {
                    for formatter in formatters {
                        if let date = formatter.dateFromString(sourceString) {
                            return date
                        }
                    }

                }
                if let sourceInt = source as? Int {
                    // treat as a java date
                    return NSDate(timeIntervalSince1970: Double(sourceInt / 1000) )
                }
                fatalError("formatter failed to parse \(source)")
            } 

            // Decoder for [TWAccessToken]
            Decoders.addDecoder(clazz: [TWAccessToken].self) { (source: AnyObject) -> [TWAccessToken] in
                return Decoders.decode(clazz: [TWAccessToken].self, source: source)
            }
            // Decoder for TWAccessToken
            Decoders.addDecoder(clazz: TWAccessToken.self) { (source: AnyObject) -> TWAccessToken in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = TWAccessToken()
                instance.id = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["id"])
                instance.ttl = Decoders.decodeOptional(clazz: Double.self, source: sourceDictionary["ttl"])
                instance.created = Decoders.decodeOptional(clazz: NSDate.self, source: sourceDictionary["created"])
                instance.userId = Decoders.decodeOptional(clazz: Double.self, source: sourceDictionary["userId"])
                return instance
            }


            // Decoder for [TWCategory]
            Decoders.addDecoder(clazz: [TWCategory].self) { (source: AnyObject) -> [TWCategory] in
                return Decoders.decode(clazz: [TWCategory].self, source: source)
            }
            // Decoder for TWCategory
            Decoders.addDecoder(clazz: TWCategory.self) { (source: AnyObject) -> TWCategory in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = TWCategory()
                instance.name = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["name"])
                instance.description = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["description"])
                instance.id = Decoders.decodeOptional(clazz: Double.self, source: sourceDictionary["id"])
                instance.categoryId = Decoders.decodeOptional(clazz: Double.self, source: sourceDictionary["categoryId"])
                instance.parentId = Decoders.decodeOptional(clazz: Double.self, source: sourceDictionary["parentId"])
                instance.designId = Decoders.decodeOptional(clazz: Double.self, source: sourceDictionary["designId"])
                instance.children = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["children"])
                instance.parent = Decoders.decodeOptional(clazz: AnyObject.self, source: sourceDictionary["parent"])
                return instance
            }


            // Decoder for [TWCustomer]
            Decoders.addDecoder(clazz: [TWCustomer].self) { (source: AnyObject) -> [TWCustomer] in
                return Decoders.decode(clazz: [TWCustomer].self, source: source)
            }
            // Decoder for TWCustomer
            Decoders.addDecoder(clazz: TWCustomer.self) { (source: AnyObject) -> TWCustomer in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = TWCustomer()
                instance.firstName = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["firstName"])
                instance.lastName = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["lastName"])
                instance.realm = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["realm"])
                instance.username = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["username"])
                instance.credentials = Decoders.decodeOptional(clazz: AnyObject.self, source: sourceDictionary["credentials"])
                instance.challenges = Decoders.decodeOptional(clazz: AnyObject.self, source: sourceDictionary["challenges"])
                instance.email = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["email"])
                instance.emailVerified = Decoders.decodeOptional(clazz: Bool.self, source: sourceDictionary["emailVerified"])
                instance.status = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["status"])
                instance.created = Decoders.decodeOptional(clazz: NSDate.self, source: sourceDictionary["created"])
                instance.lastUpdated = Decoders.decodeOptional(clazz: NSDate.self, source: sourceDictionary["lastUpdated"])
                instance.id = Decoders.decodeOptional(clazz: Double.self, source: sourceDictionary["id"])
                instance.designs = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["designs"])
                return instance
            }


            // Decoder for [TWDesign]
            Decoders.addDecoder(clazz: [TWDesign].self) { (source: AnyObject) -> [TWDesign] in
                return Decoders.decode(clazz: [TWDesign].self, source: source)
            }
            // Decoder for TWDesign
            Decoders.addDecoder(clazz: TWDesign.self) { (source: AnyObject) -> TWDesign in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = TWDesign()
                instance.name = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["name"])
                instance.image = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["image"])
                instance.thumbnail = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["thumbnail"])
                instance.object = Decoders.decodeOptional(clazz: AnyObject.self, source: sourceDictionary["object"])
                instance.id = Decoders.decodeOptional(clazz: Double.self, source: sourceDictionary["id"])
                instance.customerId = Decoders.decodeOptional(clazz: Double.self, source: sourceDictionary["customerId"])
                instance.tags = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["tags"])
                instance.categories = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["categories"])
                instance.customer = Decoders.decodeOptional(clazz: AnyObject.self, source: sourceDictionary["customer"])
                return instance
            }


            // Decoder for [TWInlineResponse200]
            Decoders.addDecoder(clazz: [TWInlineResponse200].self) { (source: AnyObject) -> [TWInlineResponse200] in
                return Decoders.decode(clazz: [TWInlineResponse200].self, source: source)
            }
            // Decoder for TWInlineResponse200
            Decoders.addDecoder(clazz: TWInlineResponse200.self) { (source: AnyObject) -> TWInlineResponse200 in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = TWInlineResponse200()
                instance.count = Decoders.decodeOptional(clazz: Double.self, source: sourceDictionary["count"])
                return instance
            }


            // Decoder for [TWInlineResponse2001]
            Decoders.addDecoder(clazz: [TWInlineResponse2001].self) { (source: AnyObject) -> [TWInlineResponse2001] in
                return Decoders.decode(clazz: [TWInlineResponse2001].self, source: source)
            }
            // Decoder for TWInlineResponse2001
            Decoders.addDecoder(clazz: TWInlineResponse2001.self) { (source: AnyObject) -> TWInlineResponse2001 in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = TWInlineResponse2001()
                instance.count = Decoders.decodeOptional(clazz: Double.self, source: sourceDictionary["count"])
                return instance
            }


            // Decoder for [TWInlineResponse2002]
            Decoders.addDecoder(clazz: [TWInlineResponse2002].self) { (source: AnyObject) -> [TWInlineResponse2002] in
                return Decoders.decode(clazz: [TWInlineResponse2002].self, source: source)
            }
            // Decoder for TWInlineResponse2002
            Decoders.addDecoder(clazz: TWInlineResponse2002.self) { (source: AnyObject) -> TWInlineResponse2002 in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = TWInlineResponse2002()
                instance.exists = Decoders.decodeOptional(clazz: Bool.self, source: sourceDictionary["exists"])
                return instance
            }


            // Decoder for [TWInlineResponse2003]
            Decoders.addDecoder(clazz: [TWInlineResponse2003].self) { (source: AnyObject) -> [TWInlineResponse2003] in
                return Decoders.decode(clazz: [TWInlineResponse2003].self, source: source)
            }
            // Decoder for TWInlineResponse2003
            Decoders.addDecoder(clazz: TWInlineResponse2003.self) { (source: AnyObject) -> TWInlineResponse2003 in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = TWInlineResponse2003()
                instance.greeting = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["greeting"])
                return instance
            }


            // Decoder for [TWTag]
            Decoders.addDecoder(clazz: [TWTag].self) { (source: AnyObject) -> [TWTag] in
                return Decoders.decode(clazz: [TWTag].self, source: source)
            }
            // Decoder for TWTag
            Decoders.addDecoder(clazz: TWTag.self) { (source: AnyObject) -> TWTag in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = TWTag()
                instance.name = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["name"])
                instance.id = Decoders.decodeOptional(clazz: Double.self, source: sourceDictionary["id"])
                instance.designId = Decoders.decodeOptional(clazz: Double.self, source: sourceDictionary["designId"])
                return instance
            }


            // Decoder for [TWUser]
            Decoders.addDecoder(clazz: [TWUser].self) { (source: AnyObject) -> [TWUser] in
                return Decoders.decode(clazz: [TWUser].self, source: source)
            }
            // Decoder for TWUser
            Decoders.addDecoder(clazz: TWUser.self) { (source: AnyObject) -> TWUser in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = TWUser()
                instance.realm = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["realm"])
                instance.username = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["username"])
                instance.credentials = Decoders.decodeOptional(clazz: AnyObject.self, source: sourceDictionary["credentials"])
                instance.challenges = Decoders.decodeOptional(clazz: AnyObject.self, source: sourceDictionary["challenges"])
                instance.email = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["email"])
                instance.emailVerified = Decoders.decodeOptional(clazz: Bool.self, source: sourceDictionary["emailVerified"])
                instance.status = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["status"])
                instance.created = Decoders.decodeOptional(clazz: NSDate.self, source: sourceDictionary["created"])
                instance.lastUpdated = Decoders.decodeOptional(clazz: NSDate.self, source: sourceDictionary["lastUpdated"])
                instance.id = Decoders.decodeOptional(clazz: Double.self, source: sourceDictionary["id"])
                return instance
            }
        }
    }
}
