//
// MessageAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class MessageAPI: APIBase {
    /**

     - parameter msg: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func messageGreet(msg msg: String? = nil, completion: ((data: TWInlineResponse2003?, error: ErrorType?) -> Void)) {
        messageGreetWithRequestBuilder(msg: msg).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     - GET /Messages/greet
     - API Key:
       - type: apiKey access_token (QUERY)
       - name: access_token
     - examples: [{contentType=application/json, example={
  "greeting" : "aeiou"
}}]
     
     - parameter msg: (query)  (optional)

     - returns: RequestBuilder<TWInlineResponse2003> 
     */
    public class func messageGreetWithRequestBuilder(msg msg: String? = nil) -> RequestBuilder<TWInlineResponse2003> {
        let path = "/Messages/greet"
        let URLString = TweakApiAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "msg": msg
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<TWInlineResponse2003>.Type = TweakApiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
