//
// TWAccessToken.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class TWAccessToken: JSONEncodable {
    public var id: String?
    /** time to live in seconds (2 weeks by default) */
    public var ttl: Double?
    public var created: NSDate?
    public var userId: Double?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["ttl"] = self.ttl
        nillableDictionary["created"] = self.created?.encodeToJSON()
        nillableDictionary["userId"] = self.userId
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
