//
// TWCategory.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class TWCategory: JSONEncodable {
    public var name: String?
    public var description: String?
    public var id: Double?
    public var categoryId: Double?
    public var parentId: Double?
    public var designId: Double?
    public var children: [AnyObject]?
    public var parent: AnyObject?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["description"] = self.description
        nillableDictionary["id"] = self.id
        nillableDictionary["categoryId"] = self.categoryId
        nillableDictionary["parentId"] = self.parentId
        nillableDictionary["designId"] = self.designId
        nillableDictionary["children"] = self.children?.encodeToJSON()
        nillableDictionary["parent"] = self.parent
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
