//
// TWDesign.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class TWDesign: JSONEncodable {
    public var name: String?
    public var image: String?
    public var thumbnail: String?
    public var object: AnyObject?
    public var id: Double?
    public var customerId: Double?
    public var tags: [AnyObject]?
    public var categories: [AnyObject]?
    public var customer: AnyObject?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["image"] = self.image
        nillableDictionary["thumbnail"] = self.thumbnail
        nillableDictionary["object"] = self.object
        nillableDictionary["id"] = self.id
        nillableDictionary["customerId"] = self.customerId
        nillableDictionary["tags"] = self.tags?.encodeToJSON()
        nillableDictionary["categories"] = self.categories?.encodeToJSON()
        nillableDictionary["customer"] = self.customer
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
